### PR TITLE
Refactor prompt

### PR DESCRIPTION
**Pull request by ixje**
**What current issue(s) does this address, or what feature is it adding?**
Address #623 
Huge thanks @jseagrave21 and @LysanderGG

**How did you solve this problem?**
see #623

**How did you make sure your solution works?**
make test

**Are there any special changes in the code that we should be aware of?**
I've chosen to not include #731 at this time. Mostly because I want this hard work in the development branch such that people can test it for a couple of days before we do a new release. The module loading part can be addresses at a later point. For that I want to spent a little bit more time to see how we can also support targeted loading (meaning; load the custom cmd into a specific existing sub group)

**Please check the following, if applicable:**

- [X] Did you add any tests?
- [X] Did you run `make lint`?
- [X] Did you run `make test`?
- [X] Are you making a PR to a feature branch or development rather than master?
- [X] Did you add an entry to `CHANGELOG.rst`? (if not, please do)

### CODE REVIEW

**Comment by ixje** [comment]
So this is a first; builds fine locally, fails miserably on Travis 🤔

**Comment by ixje** [comment]
also strange to see how the history shows that e.g https://github.com/CityOfZion/neo-python/pull/796 fails building, while if you go to the actual pull is clearly shows travis succeeded.
https://travis-ci.org/CityOfZion/neo-python/builds/475989612?utm_source=github_status&utm_medium=notification

**Comment by jseagrave21** [comment]
That is really weird!

**Comment by ixje** [comment]
I just manually reproduced the Travis-CI script in a fully clean environment. Still builds fine locally. If anyone has ideas, let me know.

**Comment by jseagrave21** [comment]
Hey it looks like the most recent builds passed?

Also, I was going to say maybe it is a fluke and to just close this PR and retitle #805?

**Comment by ixje** [comment]
closing in favour of #805 that does build time after time on travis-ci.

**Pull request closed without merging**
