### PR TITLE
Implement the ability to add a priority fee to applicable transactions

### PR DESCRIPTION
**Pull request by jseagrave21**
**What current issue(s) does this address, or what feature is it adding?**

- The goal for this PR is to fully implement the ability to add fees in neo-python

- Additionally, 
  - improve TokenSend by fixing the ability to add tx-attrs
  - improve TokenMint by integrating it with the token_mint function and including the ability to add invoke-attrs
  - improve TokenRegister by adding password protection (since it requires a fee)
  - remove password-prompt flags which is in line with previous PRs and CoZ/neo-python discussion on Slack

**How did you solve this problem?**
I used the same logic from Send.py for adding a fee

**How did you make sure your solution works?**
Unittest

**Are there any special changes in the code that we should be aware of?**
No

**Please check the following, if applicable:**

- [x] Did you add any tests?
- [x] Did you run `make lint`?
- [x] Did you run `make test`?
- [x] Are you making a PR to a feature branch or development rather than master?
- [x] Did you add an entry to `CHANGELOG.rst`? (if not, please do)

### CODE REVIEW

**Comment by ixje** [comment]
Sorry for the delayed review. This is a great PR and crucial addition to #869 for supporting the new SimplePolicy fee structure changes. Also eligible for rewards imo @hal0x2328

**Comment by hal0x2328** [comment]
> Also eligible for rewards imo @hal0x2328

I agree (although it's not up to me for this repo). But I say Tag it and Drag it! (into the CoZ rewards project 😃)

**Comment by ixje** [comment]
300 points jseagrave

**Comment by lllwvlvwlll** [comment]
https://neoscan.io/transaction/9b3d719cf827461cc7a85a57561f2b0de18cc3feec68777e11a8621b18bce55f

**Pull request merged**
