### PR TITLE
Changed container to Alpine Linux instead of Ubuntu

### PR DESCRIPTION
**Pull request by nunojusto**
**What current issue(s) does this address, or what feature is it adding?**
#546 

**How did you solve this problem?**
Rebuild current Dockerfile to use Alpine Linux image

**How did you make sure your solution works?**
Already tested and it's working locally

**Are there any special changes in the code that we should be aware of?**
No

### CODE REVIEW

**Comment by nunojusto** [comment]
Hi, metachris.
I know that in CoZ is kind of standard to use ubuntu and i agree with the argument of being more easy to play with package manager. But in the end is just a change aversion cause it's not so different to use apk.
There are advantages to use a lighter distro: Faster, smaller, more secure.
Some of them are already visible and I posted in my screenshot (inside the issue).

Here's a good article advocating for Alpine instead of any other.
https://nickjanetakis.com/blog/the-3-biggest-wins-when-using-alpine-as-a-base-docker-image

**Comment by i25959341** [comment]
This is awesome. I used Kubernetes for containers deployment and using Alpine would make the deployment process easier to build and more secure for containers that use neo-python. 

I think Alpine shouldn't replace the ubuntu images but should be provided as an option for DevOps like us to use, as alpine is great for production. And the Ubuntu version should be used for the development stage.

**Comment by metachris** [comment]
Let's start with this being a second Dockerfile besides the Ubuntu one and see where it is developing. Could you please rename the alpine file to `Dockerfile.alpine` or something similar?

**Comment by nunojusto** [comment]
Sure, I willl do that

**Comment by metachris** [comment]
Oh, and keep the original Dockerfile in there please :)

**Comment by nunojusto** [comment]
I hope, now that's all done

**Comment by metachris** [comment]
It seems there are still some merge conflict artifacts left over: https://github.com/CityOfZion/neo-python/pull/547/files#diff-1ec61223727a10e5e4c74c68336809fc

**Comment by nunojusto** [comment]
Clean

**Comment by nunojusto** [comment]
ok now?

**Comment by metachris** [comment]
Thanks :+1:

**Pull request merged**
