### PR TITLE
Adding CreateAddress Feature

### PR DESCRIPTION
**Pull request by jseagrave21**
**What current issue(s) does this address, or what feature is it adding?**
Adds CreateAddress Feature

**How did you solve this problem?**
Referenced neo-cli and talked with @ixje 

**How did you make sure your solution works?**
Testing on my own privatenet and created a test for it.

**Are there any special changes in the code that we should be aware of?**
no.
**Please check the following, if applicable:**

- [x] Did you add any tests?
- [ ] Did you run `make lint`?
- [ ] Did you run `make test`?
- [x] Are you making a PR to a feature branch or development rather than master?
- [x] Did you add an entry to `CHANGELOG.rst`? (if not, please do)

### CODE REVIEW

**Comment by jseagrave21** [comment]
I think this is working as intended. Let me know what you think.

**Comment by localhuman** [comment]
Looks good, though the code-style check is failing

**Comment by jseagrave21** [comment]
Okay, I think I fixed the style errors.

**Comment by jseagrave21** [comment]
Thank you @ixje! I never used those before because I didn't know what they were.

**Comment by localhuman** [comment]
Nice work!

**Pull request merged**
