### PR TITLE
prompt.py style improvements, plus a more robust CLI Command Parser

### PR DESCRIPTION
**Pull request by mjakl**
**What current issue(s) does this address?, or what feature is it adding?**

During the last NEO Meetup, adding a space at the wrong spot would break the current command parser in `prompt.py`, the new implementation is aware of brackets, and quoted strings and should now allow a more natural way of writing lists (like `["arg1", "arg2"...]` instead of forcing us to squash the spaces (ie `["arg1","arg2"...]`).

**How did you solve this problem?**

I've written a parser with `pyparse` which was already an available dependency. Using a proper parser is probably the only way forward for the `prompt.py` language to get more powerful.

**How did you make sure your solution works?**

I extracted the problematic part of the code, added tests, and changed the implementation.

**Did you add any tests?**

Yes, see `neo/Prompt/test_input_parser.py`

**Are there any special changes in the code that we should be aware of?**

Besides the functional change (commit b64d721), I made some style changes (consistent use of single quotes and capital letters, closer adherence to PEP8)

### CODE REVIEW

**Comment by mjakl** [comment]
Yes, Vienna Meetup, great presentation BTW!

So, `"` is the common style? in `prompt.py` it was a mixture of both. Will fix... .

**Comment by metachris** [comment]
Thanks! And great that you're already contributing! 👍 

Yeah it's more typically doublequotes but sometimes a mix. Just don't fix that everywhere, makes the PR harder to understand. It's always better to keep the PRs simple and focused on one thing. If at all, changing quotes would be another separate PR ;-)

**Comment by mjakl** [comment]
Ok, I've split this PR into two separate ones: #180 and #181. #181 will be easier to read when #180 is applied, but it was not (easily) possible to completely separate them. I reverted some of the `'`/`"` changes (kept only the ones that are very out of style) I hope that's better?

Closing this in favour of the other two.

**Comment by mjakl** [comment]
#182 is a version of the parser without any style changes.

**Pull request closed without merging**
