### PR TITLE
[refactor-prompt] add config nep8

### PR DESCRIPTION
**Pull request by ixje**
**What current issue(s) does this address, or what feature is it adding?**
move #623 forward by

**How did you solve this problem?**
migrate

**How did you make sure your solution works?**
make test

**Are there any special changes in the code that we should be aware of?**
no

**Please check the following, if applicable:**

- [X] Did you add any tests?
- [X] Did you run `make lint`?
- [X] Did you run `make test`?
- [X] Are you making a PR to a feature branch or development rather than master?
- [ ] Did you add an entry to `CHANGELOG.rst`? (if not, please do)

### CODE REVIEW

**Comment by jseagrave21** [comment]
Does it matter that this "toggle" function doesn't follow the same example as some others already approved like "vm-log" , "sc-debug-notify", etc?

**Comment by ixje** [comment]
as in user feedback messages you mean? 
"Invalid option" vs "Cannot <feature>. Please specify on|off or 1|0"
or something else?

**Comment by jseagrave21** [comment]
Yep that's what I meant

**Comment by ixje** [comment]
Yeah I noticed and there's probably some more places where there are inconsistencies in naming/feedback used. I was planning to make a full sweep when all commands are in and align them. 

The cool thing about the `strtobool` function I recently found is that it parses a lot of different inputs.

https://docs.python.org/3.6/distutils/apiref.html#distutils.util.strtobool

I think it simplifies the code and gives more freedom to the user how they would like to express on/off.

**Comment by jseagrave21** [comment]
> Yeah I noticed and there's probably some more places where there are inconsistencies in naming/feedback used. I was planning to make a full sweep when all commands are in and align them.
:+1: 
> The cool thing about the `strtobool` function I recently found is that it parses a lot of different inputs.
> 
> https://docs.python.org/3.6/distutils/apiref.html#distutils.util.strtobool
> 
> I think it simplifies the code and gives more freedom to the user how they would like to express on/off.

Very cool! Okay looks good to me.

**Comment by ixje** [comment]
✅

**Pull request merged**
