### PR TITLE
Update/Add Asset and Contract Search Methods

### PR DESCRIPTION
**Pull request by jseagrave21**
**What current issue(s) does this address, or what feature is it adding?**

**-update-**
- Update `getassetstate` RPC method
  - Allows using "neo" or "gas" to return their assetstate
- add `showallassets` LevelDBBlockchain function
  - `showallassets` returns a list of all asset hashes
- update `SearchAssetState` LevelDBBlockchain function per https://github.com/CityOfZion/neo-python/pull/739
- update prompt.py `help`
  - update `show_asset_state` and `show_contract_state` per https://github.com/CityOfZion/neo-python/pull/741

**How did you solve this problem?**
trial and error

The inspiration for this PR comes from my work on the neo-python API reference. In most cases, assets in neo-python can be searched by their name. The contract search methods update was inspired through their tangential relationship in `prompt.py` and LevelDBBlockckchain.

**How did you make sure your solution works?**
unittest

**Are there any special changes in the code that we should be aware of?**
No

**Please check the following, if applicable:**

- [x] Did you add any tests?
- [x] Did you run `make lint`?
- [x] Did you run `make test`?
- [x] Are you making a PR to a feature branch or development rather than master?
- [x] Did you add an entry to `CHANGELOG.rst`? (if not, please do)

### CODE REVIEW

**Comment by localhuman** [comment]
Looks good, though merge conflicts will need to be fixed!

**Comment by jseagrave21** [comment]
@localhuman Okay, this PR is ready for another review.

**Comment by ixje** [comment]
If you can remove the extended RPC related code (as that was moved out now see  #756) then we can still use it to update the other parts. Thanks!

**Comment by jseagrave21** [comment]
@ixje this PR should be good to go

**Comment by jseagrave21** [comment]
@ixje this PR should be ready to go

**Comment by ixje** [comment]
Strange that I did not get a web notification. I happened to look at my email and saw that there should be updates. Thanks again 👍

**Pull request merged**
