### PR TITLE
neo/api/REST/NotificationRestApi.py

### PR DESCRIPTION
**Pull request by metachris**
**What current issue(s) does this address?, or what feature is it adding?**

Moved `neo/Implementations/Notifications/REST/NotificationServer.py` to `neo/api/REST/NotificationRestApi.py`

**How did you solve this problem?**

moving

**How did you make sure your solution works?**

test

**Did you add any tests?**

no

**Are there any special changes in the code that we should be aware of?**

no

### CODE REVIEW

**Comment by localhuman** [comment]
Though it is a REST api, my idea is that it should be solely for notifications and not a generic rest API.  So I guess I agree with moving to the new module, but not renaming `NotificationServer` to `RestApi`.  Perhaps could be renamed to `NotificationRestApi`?

**Comment by metachris** [comment]
Sure we can do that! 

The current implementation has 3 api calls: getting info about a block, address and transaction. I'm wondering what you mean with "notifications" in particular -- could you elaborate?

**Comment by metachris** [comment]
better like this? open to any suggestions ;)

**Comment by localhuman** [comment]
👍

**Pull request merged**
