### PR TITLE
[refactor-prompt] Improve send/sendmany feedback, fix default address usage

### PR DESCRIPTION
**Pull request by ixje**
**What current issue(s) does this address, or what feature is it adding?**
The `--from-addr` description of `wallet send` and `wallet sendmany` cleverly describes a default address if not specified
```
source address to take funds from (if not specified, take first address in wallet)
```
While technically it takes the first address, from a user perspective it does not always equal to the first address seen when using the `wallet` command. The discussion in #605 and the debugging session that followed led to this discovery. This means we already have a real world  use-case where this is a problem.

The PR is made to the `refactor-prompt` branch instead of `development` (where it also applies) because otherwise we'd have to migrate the solution again once we merge the `refactor-prompt` branch.

**How did you solve this problem?**
This problem is solved in 2 ways
1) we now inform the user what `neo-python`'s interpretation of the command is i.e.
```
neo> wallet send neo ALJfaEXyMgGNAdXfizQM92QyR4x11AEGPg 1                                                                                                                                       
Validate your transaction details
---------------------------------
Sending 1.0 NEO from AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y to ALJfaEXyMgGNAdXfizQM92QyR4x11AEGPg
Returning 99999851.0 NEO as change to AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y
 
Enter your password to send to the network
[Password]>
```
This allows them to validate the source address the funds are taken from.

2) if `--from-addr` is not explicitly set, then we programatically set it to what the users sees as first address when typing `wallet`.

Under the hood `wallet` takes the addresses in the wallet from the `peewee` database. However, when constructing a transaction the addresses are sorted based on `CoinReference` hash value. These 2 sorts are not necessarily the same at all times. Instead of trying to manage all places where we loop over this data, I opted to explicitly set the source address as described above.
 
**How did you make sure your solution works?**
make test & manual testing

**Are there any special changes in the code that we should be aware of?**

**Please check the following, if applicable:**

- [ ] Did you add any tests?
- [X] Did you run `make lint`?
- [X] Did you run `make test`?
- [X] Are you making a PR to a feature branch or development rather than master?
- [ ] Did you add an entry to `CHANGELOG.rst`? (if not, please do)

### CODE REVIEW

**Comment by jseagrave21** [comment]
This looks really cool. Unfortunately, I am still not having a successful relay somehow.
```
neo> wallet address create 2
Created 2 new addresses: ['AJ5nenBnaRcopmHKQWKQAghVyagp8QMopo', 'AHFqH1MBF6AdaJQvM7dBdKD38gPKJbmz2M']
neo> wallet
[I 190106 13:27:32 UserWallet:480] Script hash b'#\xba\'\x03\xc52c\xe8\xd6\xe5"\xdc2 39\xdc\xd8\xee\xe9' <class 'bytes'>[I 190106 13:27:32 UserWallet:480] Script hash b'\x19S\x91\xb3N5\x0e\x99\x05\n\xe4`\xd8\xc92\x01\xbeH\xb5Q' <class 'bytes'>
[I 190106 13:27:32 UserWallet:480] Script hash b'\x10A\xcb;\xfa\xae"\xa6\xa7\xe4U\x0e"\x0cx\xaa\xbd\xed\xc6\xc5' <class 'bytes'>
Wallet {
    "path": "neo-privnet.wallet",
    "addresses": [
        {
            "version": 0,
            "address": "AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y",
            "script_hash": "e9eed8dc39332032dc22e5d6e86332c50327ba23",
            "frozen": false,
            "votes": [],
            "balances": [
                {
                    "asset": "0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b",
                    "value": "100000000.0"
                },
                {
                    "asset": "0x602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7",
                    "value": "16024.0"
                }
            ],
            "is_watch_only": false
        },
        {
            "address": "AJ5nenBnaRcopmHKQWKQAghVyagp8QMopo",
            "script_hash": "195391b34e350e99050ae460d8c93201be48b551",
            "tokens": null
        },
        {
            "address": "AHFqH1MBF6AdaJQvM7dBdKD38gPKJbmz2M",
            "script_hash": "1041cb3bfaae22a6a7e4550e220c78aabdedc6c5",
            "tokens": null
        }
    ],
    "height": 2013,
    "percent_synced": 100,
    "synced_balances": [
        "[NEO]: 100000000.0 ",
        "[NEOGas]: 16024.0 "
    ],
    "public_keys": [
        {
            "Address": "AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y",
            "Public Key": "031a6c6fbbdf02ca351745fa86b9ba5a9452d785ac4f7fc2b7548ca2a46c4fcf4a"
        },
        {
            "Address": "AJ5nenBnaRcopmHKQWKQAghVyagp8QMopo",
            "Public Key": "03979bfe29a502c82cdca84654020697009a55553f32db0e862a03ad78311ee5d3"
        },
        {
            "Address": "AHFqH1MBF6AdaJQvM7dBdKD38gPKJbmz2M",
            "Public Key": "03a51ade8d470d76f9429ed8129b40ca861c7966f55e087f3ed786015e290c0968"
        }
    ],
    "tokens": [],
    "claims": {
        "available": "0.0",
        "unavailable": "48.0"
    }
}
neo> wallet sendmany 4
Outgoing Number 1
Asset to send:
Transaction cancelled
neo> wallet sendmany 4
Outgoing Number 1
Asset to send: neo
Address to: AJ5nenBnaRcopmHKQWKQAghVyagp8QMopo
Amount to send: 500
Outgoing Number 2
Asset to send: gas
Address to: AJ5nenBnaRcopmHKQWKQAghVyagp8QMopo
Amount to send: 100
Outgoing Number 3
Asset to send: neo
Address to: AHFqH1MBF6AdaJQvM7dBdKD38gPKJbmz2M
Amount to send: 250
Outgoing Number 4
Asset to send: gas
Address to: AHFqH1MBF6AdaJQvM7dBdKD38gPKJbmz2M
Amount to send: 50
Sending with fee: 0.0
Validate your transaction details
---------------------------------
Sending 500.0 NEO from AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y to AJ5nenBnaRcopmHKQWKQAghVyagp8QMopo
Sending 100.0 GAS from AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y to AJ5nenBnaRcopmHKQWKQAghVyagp8QMopo
Sending 250.0 NEO from AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y to AHFqH1MBF6AdaJQvM7dBdKD38gPKJbmz2M
Sending 50.0 GAS from AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y to AHFqH1MBF6AdaJQvM7dBdKD38gPKJbmz2M
Returning 99999750.0 NEO as change to AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y
Returning 15974.0 GAS as change to AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y

Enter your password to send to the network
[Password]> ***
[I 190106 13:29:01 Transaction:619] Verifying transaction: b'e477fcc4ff3be27be77b1510f391b9555a3549e78cd132fb35fbc3f9410b3980'
Relayed Tx: e477fcc4ff3be27be77b1510f391b9555a3549e78cd132fb35fbc3f9410b3980
neo> show tx e477fcc4ff3be27be77b1510f391b9555a3549e78cd132fb35fbc3f9410b3980
Could not find transaction for hash e477fcc4ff3be27be77b1510f391b9555a3549e78cd132fb35fbc3f9410b3980
neo> show tx e477fcc4ff3be27be77b1510f391b9555a3549e78cd132fb35fbc3f9410b3980
Could not find transaction for hash e477fcc4ff3be27be77b1510f391b9555a3549e78cd132fb35fbc3f9410b3980
neo> show tx e477fcc4ff3be27be77b1510f391b9555a3549e78cd132fb35fbc3f9410b3980
Could not find transaction for hash e477fcc4ff3be27be77b1510f391b9555a3549e78cd132fb35fbc3f9410b3980
neo> wallet
[I 190106 13:31:13 UserWallet:480] Script hash b'#\xba\'\x03\xc52c\xe8\xd6\xe5"\xdc2 39\xdc\xd8\xee\xe9' <class 'bytes'>[I 190106 13:31:13 UserWallet:480] Script hash b'\x19S\x91\xb3N5\x0e\x99\x05\n\xe4`\xd8\xc92\x01\xbeH\xb5Q' <class 'bytes'>
[I 190106 13:31:13 UserWallet:480] Script hash b'\x10A\xcb;\xfa\xae"\xa6\xa7\xe4U\x0e"\x0cx\xaa\xbd\xed\xc6\xc5' <class 'bytes'>
Wallet {
    "path": "neo-privnet.wallet",
    "addresses": [
        {
            "version": 0,
            "address": "AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y",
            "script_hash": "e9eed8dc39332032dc22e5d6e86332c50327ba23",
            "frozen": false,
            "votes": [],
            "balances": [
                {
                    "asset": "0xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b",
                    "value": "100000000.0"
                },
                {
                    "asset": "0x602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7",
                    "value": "16024.0"
                }
            ],
            "is_watch_only": false
        },
        {
            "address": "AJ5nenBnaRcopmHKQWKQAghVyagp8QMopo",
            "script_hash": "195391b34e350e99050ae460d8c93201be48b551",
            "tokens": null
        },
        {
            "address": "AHFqH1MBF6AdaJQvM7dBdKD38gPKJbmz2M",
            "script_hash": "1041cb3bfaae22a6a7e4550e220c78aabdedc6c5",
            "tokens": null
        }
    ],
    "height": 2025,
    "percent_synced": 100,
    "synced_balances": [
        "[NEO]: 0.0 ",
        "[NEOGas]: 0.0 "
    ],
    "public_keys": [
        {
            "Address": "AK2nJJpJr6o664CWJKi1QRXjqeic2zRp8y",
            "Public Key": "031a6c6fbbdf02ca351745fa86b9ba5a9452d785ac4f7fc2b7548ca2a46c4fcf4a"
        },
        {
            "Address": "AJ5nenBnaRcopmHKQWKQAghVyagp8QMopo",
            "Public Key": "03979bfe29a502c82cdca84654020697009a55553f32db0e862a03ad78311ee5d3"
        },
        {
            "Address": "AHFqH1MBF6AdaJQvM7dBdKD38gPKJbmz2M",
            "Public Key": "03a51ade8d470d76f9429ed8129b40ca861c7966f55e087f3ed786015e290c0968"
        }
    ],
    "tokens": [],
    "claims": {
        "available": "0.0",
        "unavailable": "0.0"
    }
}
```

**Comment by ixje** [comment]
Did you wait with using `wallet` until the tx was found? Meaning `show tx e477fcc4ff3be27be77b1510f391b9555a3549e78cd132fb35fbc3f9410b3980` works? 

Otherwise there's no point in using `wallet` again. In all my local testing I could find the transaction that was send and then `wallet` showed updated funds. 

What version are the nodes of you private network that you test against? I'm testing against `2.8.0`

**Comment by jseagrave21** [comment]
I am also testing against `2.8.0`. For some reason the transaction just didn't go through. Were you able to replicate my steps above and see the tx?

**Comment by ixje** [comment]
merging, because the issue described in your comment is reported in #801 and separate from what was introduced here.

**Comment by jseagrave21** [comment]
Like I said above, I really like the user feedback! It is super clean and informative.

**Pull request merged**
