### PR TITLE
Fix InvocationTransaction Size Calculation

### LINKED ISSUE #918: Align invocation txn size calculation with C#
### Current behavior
The current invocation txn size calculation is done as [follow](https://github.com/CityOfZion/neo-python/blob/master/neo/Core/TX/InvocationTransaction.py#L32): 

```python
def Size(self):
        """
        Get the total size in bytes of the object.
        Returns:
            int: size.
        """
        return super(InvocationTransaction, self).Size() + GetVarSize(self.Script)
```

### Expected behavior
It should be done like in [¢#](https://github.com/neo-project/neo/blob/master/neo/Network/P2P/Payloads/InvocationTransaction.cs#L15) by taking into consideration the version logic whch detemines whether to add the gas size or not.
```C#
public override int Size => base.Size  // Transaction base size
           + Script.GetVarSize()               // Script variable size
           + (Version >= 1 ? Gas.Size : 0);    // Gas Fixed8 size (for version >= 1)
```

### How to reproduce
https://github.com/neo-project/neo/issues/652

### Your environment

Let us know in what environment you're running into the issue:

- OS: Ubuntu 18.X
- neo-python version: v0.8.5-dev
- Python version: 3.6

### PR DESCRIPTION
**Pull request by dauTT**
**What current issue(s) does this address, or what feature is it adding?**
Closes #918 

**How did you solve this problem?**
Added version logic to the Size calculation following the C# implementation

**How did you make sure your solution works?**
Added test case and check the result manually

**Are there any special changes in the code that we should be aware of?**

**Please check the following, if applicable:**

- [X] Did you add any tests?
- [ ] Did you run `make lint`?
- [X] Did you run `make test`?
- [X] Are you making a PR to a feature branch or development rather than master?
- [X] Did you add an entry to `CHANGELOG.rst`? (if not, please do)

### CODE REVIEW

**Comment by dauTT** [comment]
All the tests passed. Why Travis is complaining?

**Comment by LysanderGG** [comment]
```
$ pycodestyle neo
neo/Core/TX/test_transactions.py:16:1: E302 expected 2 blank lines, found 1
The command "pycodestyle neo" exited with 1.
```

**Comment by ixje** [comment]
thanks!

**Comment by ixje** [comment]
50 points dauTT

**Comment by lllwvlvwlll** [comment]
https://neoscan.io/transaction/d5ae4a22ffe49912a2a3dc698d39ac63a8fcf2cef63ae136850d039c312591d8

**Pull request merged**
