### PR TITLE
Fixes CityOfZion/neo-python#344 block synchronization being behind with one block

### PR DESCRIPTION
**Pull request by MediaServe**
**What current issue(s) does this address, or what feature is it adding?**
CityOfZion/neo-python#344
Block height is always 1 block behind in synchronization

**How did you solve this problem?**
Found a `- 1` in the HeaderHeight property that I believe should not be there. 

**How did you make sure your solution works?**
Tested synchornization and block retrieval, compared to `neo-cli` implementation

**Are there any special changes in the code that we should be aware of?**
I don't think so

### CODE REVIEW

**Comment by metachris** [comment]
Thanks.

A small change, but might have bigger impact. Great that you checked conformity with neo-cli! @localhuman what's your thoughts on this?

**Comment by MediaServe** [comment]
It probably needs more extensive testing before merging. I'm going to do more testing and let you know my results.

**Comment by localhuman** [comment]
I would not make this change this way, as this matches the current C# implementation of `HeaderHeight`.  
https://github.com/neo-project/neo/blob/master/neo/Implementations/Blockchains/LevelDB/LevelDBBlockchain.cs#L34

There is probably a different solution to this issue 😉

**Comment by MediaServe** [comment]
Thanks! I agree that the proposed change is more a workaround than a fix. I couldn't find any other flaws in the synchronization logic. For now the change seems to work well.  I'll keep looking for a better way to fix the issue. - Thomas Lobker

**Pull request closed without merging**
