### PR TITLE
Fix Bug With Edge Case Gas Calc

### PR DESCRIPTION
**Pull request by brianlenz**
**What current issue(s) does this address, or what feature is it adding?**

Transactions consuming GAS > 9 and <=10 fail currently due to no network fee being attached to the transaction.

**How did you solve this problem?**

Fixed the GAS consumed check so that it is aligned with the NEO core reference implementation:

https://github.com/neo-project/neo-gui/blob/master/neo-gui/UI/InvokeContractDialog.cs#L37
https://github.com/neo-project/neo-gui/blob/master/neo-gui/UI/InvokeContractDialog.cs#L153

See changeset notes for more details.

**How did you make sure your solution works?**

Tested it heavily before and after.

Before:
```
Used 9.585 Gas 

---------------------------------
Test invoke successful
Total operations: 3226
Results ['Integer: 7 ']
Invoke TX GAS cost: 0.0
Invoke TX fee: 0.0
---------------------------------
```

After:
```
Used 9.585 Gas 

---------------------------------
Test invoke successful
Total operations: 3226
Results ['Integer: 7 ']
Invoke TX GAS cost: 0.0
Invoke TX fee: 0.001
---------------------------------
```

**Are there any special changes in the code that we should be aware of?**

No.

**Please check the following, if applicable:**

- [X] Did you add any tests?
- [X] Did you run `make lint`?
- [X] Did you run `make test`?
- [X] Are you making a PR to a feature branch or development rather than master?
- [X] Did you add an entry to `CHANGELOG.rst`? (if not, please do)

### CODE REVIEW

**Comment by metachris** [comment]
Very nice!

**Comment by brianlenz** [comment]
This change is worthy of a test, so I'm going to add one shortly.

**Comment by brianlenz** [comment]
OK, test added!

**Comment by localhuman** [comment]
This is great, thanks!

**Pull request merged**
