### PR TITLE
prompt store history and log in custom datadir

### PR DESCRIPTION
**Pull request by metachris**
**What current issue(s) does this address, or what feature is it adding?**

If user uses a custom data-dir with `--datadir`, np-prompt should store log and history there. Before it would just use `~/.neopython/`.

**How did you solve this problem?**

Removing temporary user-data paths in settings, and updating prompt.py slightly to use the correct base directory.

Did a small refactoring to Settings.py, to not have the temporary user paths anymore.

Note: I left the explicit setting of testnet in the examples because it illustrates what you should do where, helps the examples to make this explicit.

**How did you make sure your solution works?**

Manual tests

**Are there any special changes in the code that we should be aware of?**

no (TestNet is still used by default)

**Please check the following, if applicable:**

- [ ] Did you add any tests?
- [X] Did you run `make lint`?
- [X] Did you run `make test`?
- [X] Are you making a PR to a feature branch or development rather than master?
- [X] Did you add an entry to `CHANGELOG.rst`? (if not, please do)

### CODE REVIEW

**Comment by localhuman** [comment]
Looks good to me! Would be interested how others feel!

**Comment by brianlenz** [comment]
I like it 👍 Should the changelog mention that if you use a custom `--datadir` that your `np-prompt` history will reset?

**Comment by metachris** [comment]
Good idea @brianlenz. Updated.

**Comment by metachris** [comment]
Gonna merge this if no more comments or objections

**Pull request merged**
