### PR TITLE
High Volume GAS Claim Improvement

### PR DESCRIPTION
**Pull request by brianlenz**
**What current issue(s) does this address, or what feature is it adding?**

Addresses with thousands of UTXOs may have issues with transaction size preventing GAS claims from working in neo-python.

@localhuman: will be curious to hear your thoughts on this. Does the approach seem reasonable? Necessary? Anything that could be better about it?

**How did you solve this problem?**

Claim GAS for at most 200 UTXOs at a time.

**How did you make sure your solution works?**

Tested and used the process.

**Are there any special changes in the code that we should be aware of?**

No.

**Please check the following, if applicable:**

- [ ] Did you add any tests?
- [X] Did you run `make lint`?
- [X] Did you run `make test`?
- [X] Are you making a PR to a feature branch or development rather than master?
- [X] Did you add an entry to `CHANGELOG.rst`? (if not, please do)

### CODE REVIEW

**Comment by localhuman** [comment]
Is there an example / test /use case where addresses with lots of claimable are currently failingl?

**Comment by brianlenz** [comment]
I've had this happen a couple of times, and the only fix I found was to chunk through the claims incrementally (which has worked without issue). The main use case for us was with our token sale SC address, which had 2k-3k claims available. At two different points in time (mid-sale and post-sale), I had tried using the standard claim process, and the tx would never go through. It would break the state of the wallet, and I'd have to rebuild the wallet. I suspected size was the issue, so I started playing around with it. I tried chunks of 500 claims at a time, and that didn't work. I found the only way around it was to chunk through the transactions in smaller increments, and 200 seemed to work in our case. It's definitely not scientific in any way, which is why I was curious to get your thoughts. If this is something that shouldn't technically be necessary, then perhaps there is some separate issue that needs to be addressed (and this approach scrapped altogether).

**Comment by localhuman** [comment]
Thanks for the explanation.  I'd be interested in the root cause of the issue, but would have to be able to reproduce to determine that.  I wonder if maybe we're running into the max size of a transaction?  

Perhaps for now it would be best to allow users to pass in the size of the chunk, otherwise it defaults to current behavior?

**Comment by brianlenz** [comment]
I like that idea! I'll take a crack at it :)

**Comment by brianlenz** [comment]
Should be good to go now, I believe.

**Comment by localhuman** [comment]
Thanks for the changes!

**Pull request merged**
