### PR TITLE
return type must be bigint

### PR DESCRIPTION
**Pull request by igormcoelho**
**What current issue(s) does this address, or what feature is it adding?**

According to a fruitful discussion in neo project ( https://github.com/neo-project/neo/pull/253 ), we concluded that the return type must be coded as a BigInteger, not a simple hex... For most types it doesn't matter (eg. boolean is 01, and BigInt(1).toHex is also 01), but for Void, the neo machine expects to receive \xff00 which is the real BigInt(255), not \xff, which is BigInt(-1)... This will also cause problems with InteropInterface type, that is passing now as \xf0, but it's supposed to be the BigInt representation of it.

**How did you solve this problem?**

Struggling for many months, and this last discussion in NEO: https://github.com/neo-project/neo/pull/253

**How did you make sure your solution works?**

This works already on Eco platform (neocompiler.io), when building transactions correctly.
On neo-python, I haven't tested well yet... this may have some impacts in FunctionCode, and I still haven't time to view all of it yet. But still, this needs to be fixed as soon as possible, in order to avoid other strange errors (such as https://github.com/CityOfZion/neo-python/pull/422 and https://github.com/CityOfZion/neo-python/issues/217)

**Are there any special changes in the code that we should be aware of?**

Not yet, we have to see the impacts.

**Please check the following, if applicable:**

- [ ] Did you add any tests?
- [x] Did you run `make lint`?
- [ ] Did you run `make test`?
- [X] Are you making a PR to a feature branch or development rather than master?
- [ ] Did you add an entry to `CHANGELOG.rst`? (if not, please do)

### CODE REVIEW

**Comment by igormcoelho** [comment]
please dont take a look at this yet.i will improve and try to put some tests, when I have time

**Comment by canesin** [comment]
@igormcoelho I am reopening this, you can commit any test fix directly to your branch and it will appear in the PR automatically. Thanks for the catch.

**Comment by igormcoelho** [comment]
Guys, `make test` is still failing (on 6 cases) and I don't have any idea on the outcome (they are complaining on some `TypeError: 'module' object is not callable`, but that should be some random message, I don't know the exact failures). Sorry, but I don't know if I will manage to finish all these tests, my time is quite constrained and I was just trying to help. If someone else manages to finish this, I believe it's a good direction (better a breaking code than a code that compiles but has misleading behavior).

**Comment by localhuman** [comment]
I can take a look

**Comment by localhuman** [comment]
Closing this in favor of #448

**Pull request closed without merging**
