### PR TITLE
Fix InputParser

### PR DESCRIPTION
**Pull request by jseagrave21**
**What current issue(s) does this address, or what feature is it adding?**
- addresses #954 
  - parse nested lists correctly

**How did you solve this problem?**
trial and error

**How did you make sure your solution works?**
manual testing and `make test`

**Are there any special changes in the code that we should be aware of?**
no

**Please check the following, if applicable:**

- [x] Did you add any tests?
- [x] Did you run `make lint`?
- [x] Did you run `make test`?
- [x] Are you making a PR to a feature branch or development rather than master?
- [x] Did you add an entry to `CHANGELOG.rst`? (if not, please do)

### CODE REVIEW

**Comment by jseagrave21** [comment]
@ixje I haven't been able to figure out the issue yet. If you run this test:
```
def test_nested_lists_3(self):
        command, arguments = self.input_parser.parse_input('sc build_run sc.py False False False 0210 01 3 ["notused",["notused",["helloworld"]]]')
        self.assertEqual(command, "sc")
        self.assertEqual(arguments, ['build_run', 'sc.py', 'False', 'False', 'False', '0210', '01', '3', '["notused",["notused",["helloworld"]]]'])
```
it passes.

This is the error that is causing the problem.
```
neo> sc build_run /mnt/c/users/jseag/neo/smartcontracts/ParseListTest.py False False False 0210 01 3 ["notused",["notused",["helloworld"]]]
Saved output to /mnt/c/users/jseag/neo/smartcontracts/ParseListTest.avm
Could not execute command: argument should be bytes, buffer or ASCII string, not 'list'
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/venv/bin/np-prompt", line 11, in <module>
    load_entry_point('neo-python', 'console_scripts', 'np-prompt')()
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/neo/bin/prompt.py", line 380, in main
    loop.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 521, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1738, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/neo/bin/prompt.py", line 232, in run
    traceback.print_stack()
Traceback (most recent call last):
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/neo/bin/prompt.py", line 218, in run
    cmd.execute(arguments)
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/neo/Prompt/Commands/SC.py", line 44, in execute
    return self.execute_sub_command(item, arguments[1:])
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/neo/Prompt/CommandBase.py", line 75, in execute_sub_command
    return self.__sub_commands[id].execute(arguments)
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/neo/Prompt/Commands/SC.py", line 80, in execute
    tx, result, total_ops, engine = BuildAndRun(arguments, PromptData.Wallet)
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/neo/Prompt/Commands/BuildNRun.py", line 72, in BuildAndRun
    debug_map=debug_map, invoke_attrs=invoke_attrs, owners=owners, enable_debugger=enable_debugger)
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/neo/Prompt/Commands/BuildNRun.py", line 95, in DoRun
    invoke_attrs=invoke_attrs, owners=owners, enable_debugger=enable_debugger)
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/neo/Prompt/Commands/Invoke.py", line 519, in test_deploy_and_invoke
    sb.push(subsub)
  File "/mnt/c/users/jseag/neo/neo-python-jseagrave21/neo/VM/ScriptBuilder.py", line 110, in push
    buf = binascii.unhexlify(data)
TypeError: argument should be bytes, buffer or ASCII string, not 'list'
```
Do you see what is wrong? I will keep working on it.

**Comment by ixje** [comment]
https://github.com/CityOfZion/neo-python/blob/7e292275298794d6286b755f32297132528af107/neo/VM/ScriptBuilder.py#L91

`push()` does not seem to know how to handle a `list` as its last resort is to treat it like a `bytearray`. Maybe there is a good reason for that, can't quickly tell. Try looking at C#'s ScriptBuilder and see what they do with arrays, perhaps they already have a way of dealing with them.

**Comment by jseagrave21** [comment]
@ixje okay, how about now?

**Comment by ixje** [comment]
thanks!

**Comment by ixje** [comment]
100 points

**Comment by lllwvlvwlll** [comment]
https://neoscan.io/transaction/589328c622e101065f6717d61a332f93aac71cc68b665e194ef8c874a7e26669

**Comment by nimmortal** [comment]
Hello, when this fix will be available in master?

**Comment by ixje** [comment]
We are currently auditing the Mainnet to ensure correctness with the latest `neo-cli` version as used in the consensus nodes. Once that is done we will do a new master release. Unfortunately I can't give an exact time frame, but it's around 70% done.

**Comment by ixje** [comment]
In the meantime you could cherry pick this PR

**Pull request merged**
