### PR TITLE
update requirements for doc creation

### PR DESCRIPTION
**Pull request by ixje**
**What current issue(s) does this address, or what feature is it adding?**
the requirements for just creating documentation were heavily outdated. 

**How did you solve this problem?**
created a fresh install/venv, `make doc`'ed + `pip install` until all missing packages were resolved.

**How did you make sure your solution works?**
`make doc`
**Are there any special changes in the code that we should be aware of?**
no
**Please check the following, if applicable:**

- [ ] Did you add any tests?
- [X] Did you run `make lint`?
- [ ] Did you run `make test`?
- [X] Are you making a PR to a feature branch or development rather than master?
- [ ] Did you add an entry to `CHANGELOG.rst`? (if not, please do)

### CODE REVIEW

**Comment by localhuman** [comment]
Last time I checked, the Read the Docs server that builds the docs can only be done with Python 3.5, so I know upgrading neo-boa ( which won't work with 3.5 ) will break the docs server build.

**Comment by ixje** [comment]
Oh didn't know that. I only tested locally. Any way to test without pushing here?
I think there's a good chance python 3.6 is now supported, see:
* https://github.com/rtfd/readthedocs.org/pull/3817
* https://github.com/rtfd/readthedocs.org/pull/3814#discussion_r175231510

**Comment by localhuman** [comment]
That would be great if they're supporting 3.6 venv now!  I can switch the build to the development branch to see if it works after merging this-

**Comment by ixje** [comment]
I'll leave it up to you to take further then 👍

**Pull request merged**
