### PR TITLE
Reduce Test Fixture Size

### PR DESCRIPTION
**Pull request by dauTT**
**What current issue(s) does this address, or what feature is it adding?**

#478, #554

**How did you solve this problem?**

With the help of @ixje  and @jseagrave21 , we have migrated all the unit test cases which depend on `BlockChainFixtureTestCase` and `ẀalletFixtureTestCase` to a privnet image. As a side effect issue #554 is also fixed. A big THANK to them for this PR. :smile: 

**How did you make sure your solution works?**

Run all tests individually and collectively. 

**Are there any special changes in the code that we should be aware of?**

There are new fixtures that we need to upload to AWS. They can be found here: [link](https://github.com/CityOfZion/neo-python/issues/478#issuecomment-422587158)

We have also added a new configuration setting (data/protocol.unittest-net.json) which is specifically used for running the unittest. The new setup for adding test cases is based on a [neo-privnet-unittest](https://hub.docker.com/r/dautt/neo-privnet-unittest/) image. More guideline on how to add new test cases will be given in due course of time. 

**Please check the following, if applicable:**

- [x] Did you add any tests?
- [x] Did you run `make lint`?
- [x] Did you run `make test`?
- [x] Are you making a PR to a feature branch or development rather than master?
- [x] Did you add an entry to `CHANGELOG.rst`? (if not, please do)

### CODE REVIEW

**Comment by jseagrave21** [comment]
:+1:

**Comment by jseagrave21** [comment]
I am thinking Travis will pass once the new fixtures are uploaded to AWS.

**Comment by jseagrave21** [comment]
Also, I recommend changing the title of the PR to something more descriptive, like "Reduce Test Fixture Size"

**Comment by ixje** [comment]
So there's a chicken egg problem here; `neo-python` as a dependency or coupling with `neo-boa`, so the build system also validates that `neo-boa` is still working as intended. `neo-boa` has test depending on `WalletFixtures`. To solve this we first merge the PR into a separate branch on the main repo so we can point `neo-boa`'s build system to this branch and fix the tests

**Pull request merged**
