### PR TITLE
Support #888

### PR DESCRIPTION
**Pull request by jseagrave21**
**What current issue(s) does this address, or what feature is it adding?**
Supports https://github.com/CityOfZion/neo-python-core/pull/169 which addresses #888.

**How did you solve this problem?**
See https://github.com/CityOfZion/neo-python-core/pull/169

**How did you make sure your solution works?**
`make test`

**Are there any special changes in the code that we should be aware of?**
No

**Please check the following, if applicable:**

- [ ] Did you add any tests?
- [x] Did you run `make lint`?
- [x] Did you run `make test`?
- [x] Are you making a PR to a feature branch or development rather than master?
- [x] Did you add an entry to `CHANGELOG.rst`? (if not, please do)

### CODE REVIEW

**Comment by ixje** [comment]
2 small requests; 
1) can you point travis to the development branch of `neo-python-core`. I just created that and already holds your core exception changes. So this change will allow us to continue working without having to already do a `neo-python-core` and `neo-python` release.

Before
https://github.com/CityOfZion/neo-python/blob/fe90f62e123d720d4281c79af0598d9df9e776fb/.travis.yml#L24

After
```
 - pip install -e git+https://github.com/CityOfZion/neo-python-core@development#egg=neocore 
```

2) please resolve the changelog

**Comment by ixje** [comment]
💪

**Comment by ixje** [comment]
200 points jseagrave

**Comment by lllwvlvwlll** [comment]
https://neoscan.io/transaction/d5ae4a22ffe49912a2a3dc698d39ac63a8fcf2cef63ae136850d039c312591d8

**Pull request merged**
