### PR TITLE
Update .pyup.yml

### PR DESCRIPTION
**Pull request by LysanderGG**
**What current issue(s) does this address, or what feature is it adding?**
Explicitly set the branch to merge against

**How did you solve this problem?**
.

**How did you make sure your solution works?**
.

**Are there any special changes in the code that we should be aware of?**
No.
However, I think that this should be merged to master in order for pyup to read it.

**Please check the following, if applicable:**

- [ ] Did you add any tests?
- [ ] Did you run `make lint`?
- [ ] Did you run `make test`?
- [ ] Are you making a PR to a feature branch or development rather than master?
- [ ] Did you add an entry to `CHANGELOG.rst`? (if not, please do)

### CODE REVIEW

**Comment by ixje** [comment]
looks good. On a side note; any idea why the "weekly" settings might not have worked. I closed ~30 individual PR's

**Comment by LysanderGG** [comment]
The file is only on develop, as long as it is not on master it won't be taken into account I think.

**Comment by ixje** [comment]
d'oh, totally overlooked that. I thought it was on master. Can you change the destination branch?

**Comment by ixje** [comment]
Thanks. I'll re-enable pyup shortly 🤞

**Pull request merged**
