### PR TITLE
NEP2 Support for KeyPair (fixes #65)

### LINKED ISSUE #65: [Feature] Implement NEP 2 for wallet
Implement NEP2 standard for passphrase protection outlined here:

https://github.com/neo-project/proposals/blob/master/nep-2.mediawiki

### PR DESCRIPTION
**Pull request by metachris**
**What current issue(s) does this address?, or what feature is it adding?**

Added NEP2 encrypted key support to KeyPair. See #65

**How did you solve this problem?**

Adding NEP2 encrypted key support to KeyPair. @ixje helped with testing and finalizing the solution.

**How did you make sure your solution works?**

Tests

**Did you add any tests?**

Yes

**Did you check your `pycodestyle`?**

Yes

**Are there any special changes in the code that we should be aware of?**

No

**Are you making a PR to a feature branch or development rather than master?**

development

### CODE REVIEW

**Comment by metachris** [comment]
Good point about the docstrings @ixje, thx! I'll add more to this PR.

**Comment by metachris** [comment]
@ixje Added some docstrings, formatted like this: http://www.sphinx-doc.org/en/stable/ext/example_google.html

**Comment by localhuman** [comment]
Great work @metachris @ixje! 

My only feedback would be to prefer [rST doc format](https://www.python.org/dev/peps/pep-0287/), mostly to keep it in line with the docs for [neo-boa](http://neo-boa.readthedocs.io/en/latest/_modules/boa/compiler.html#Compiler)

**Comment by localhuman** [comment]
I will merge this now so we can merge in the `feature-claim` changes.  Though we'll have to address our choice of docstring format :)

**Pull request merged**
