### PR TITLE
Initial Django inspired component loading

### PR DESCRIPTION
**Pull request by ixje**
**What current issue(s) does this address, or what feature is it adding?**
A different approach for loading plugins as suggested in #699, Django inspired

**How did you solve this problem?**
add a class loader

**How did you make sure your solution works?**
manually run `api_server.py` with Rest and RPC servers

**Are there any special changes in the code that we should be aware of?**
Yes; the `RPC_SERVER` and `REST_SERVER` variables are now stored at module level and not part of the `SettingsHolder` class. The implication is that all networks (main/test/priv) use the same settings. The alternative is moving it into the `SettingsHolder` which means we need to update all `protocol.xxx.json` files to include new keys to load from and otherwise have a sane default.

What approach would be preferred here (requesting extra opinions 🙏 ): @metachris @jseagrave21 @ThomasLobker @dethos 
choice 1: all networks have the same plugin loading settings
choice 2: all network can have individual plugin loading settings as defined in their `protocol.xxx.json`

**Please check the following, if applicable:**

- [ ] Did you add any tests?
- [X] Did you run `make lint`?
- [ ] Did you run `make test`?
- [X] Are you making a PR to a feature branch or development rather than master?
- [X] Did you add an entry to `CHANGELOG.rst`? (if not, please do)

### CODE REVIEW

**Comment by ixje** [comment]
PS: Don't merge yet. If this was the intended idea then I'll also have to update the documentation to remove any `ExtendedJsonRpc` references and make some note that there will be/is a plugin for it

**Comment by jseagrave21** [comment]
I may not fully understand the implications, but I think simpler is better. If we could make one change to update the mainnet, testnet, privnet settings between "default" and "extended", I think that is okay, since a user is usually only using one instance at time.

Either way, I think _good documentation_ will allow for a user to operate the servers in the new way regardless of the implementation.

**Comment by localhuman** [comment]
Looks good!  I think the only problem is that a user who installed from pip could not specify which plugin to use without editing the installed settings file.

I think choice 2 would allow for that.  As long as we have sensible defaults for when plugins aren't specified in `protocol.xxx.json` we should be ok to allow for configuring plugins via that file.

**Comment by ixje** [comment]
This should be it, I didn't see any documentation that referenced the `ExtendedJsonRpc` server.

**Comment by jseagrave21** [comment]
> PS: Don't merge yet. If this was the intended idea then I'll also have to update the documentation to remove any `ExtendedJsonRpc` references and make some note that there will be/is a plugin for it

@ixje Are you adding instructions in this PR on how to use the new setup. Or could you implement those instructions with https://github.com/CityOfZion/neo-python/pull/664?

**Comment by ixje** [comment]
For the time being I'm not adding the instructions with this PR. We should document this at a point though.

**Pull request merged**
