### PR TITLE
np-api-server auto exit

### PR DESCRIPTION
**Pull request by jseagrave21**
**What current issue(s) does this address, or what feature is it adding?**
Partially addresses https://github.com/CityOfZion/neo-python/issues/1020, specifically issues 1-3. Now, the program will automatically exit whenever an issue arises when opening a wallet or setting minpeers/maxpeers.

I haven't figured out how to solve issue 4 from https://github.com/CityOfZion/neo-python/issues/1020.

(-edit-) All issues from https://github.com/CityOfZion/neo-python/issues/1020 have been addressed thanks to input from @ixje 

**How did you solve this problem?**
I replaced applicable instances of `return` with `raise SystemExit` which had precedence for issues setting `port-rpc` and `port-rest`.

**How did you make sure your solution works?**
Manual testing

**Are there any special changes in the code that we should be aware of?**
No.

**Please check the following, if applicable:**

- [ ] Did you add any tests?
- [x] Did you run `make lint`?
- [x] Did you run `make test`?
- [x] Are you making a PR to a feature branch or development rather than master?
- [x] Did you add an entry to `CHANGELOG.rst`? (if not, please do)

### CODE REVIEW

**Comment by ixje** [comment]
Can you please include the fix from this https://github.com/CityOfZion/neo-python/issues/1020#issuecomment-533987238 into your PR?

**Comment by ixje** [comment]
Issue 4 can be solved by changing
https://github.com/CityOfZion/neo-python/blob/5fe7d51ef14614ff1cd0681f8fe2cb3e2cb76557/neo/bin/api_server.py#L272
to
```python
runner = web.AppRunner(api_server_rpc.app, handle_signals=True)
```

Note: it will not shutdown instantly but will do it asynchronously. We can't seem to control that. It's up to the `aiohttp` package when it decides to run the handlers *shrug*

**Comment by jseagrave21** [comment]
> Can you please include the fix from this [#1020 (comment)](https://github.com/CityOfZion/neo-python/issues/1020#issuecomment-533987238) into your PR?

@ixje will do. Thank you!

**Comment by ixje** [comment]
💯

**Pull request merged**
