### PR TITLE
Improve Tokens.py

### PR DESCRIPTION
**Pull request by jseagrave21**
**What current issue(s) does this address, or what feature is it adding?**
- Improves Tokens.py
- Increases test coverage
- Add the ability to attach user attributes when sending tokens

**How did you solve this problem?**
trial and error

**How did you make sure your solution works?**
unittest

**Are there any special changes in the code that we should be aware of?**
No

**Please check the following, if applicable:**

- [x] Did you add any tests?
- [x] Did you run `make lint`?
- [x] Did you run `make test`?
- [x] Are you making a PR to a feature branch or development rather than master?
- [x] Did you add an entry to `CHANGELOG.rst`? (if not, please do)

### CODE REVIEW

**Comment by jseagrave21** [comment]
Failing on this error:
```
======================================================================
FAIL: test_binops (boa_test.tests.test_binops.TestContract)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/src/neo-boa/boa_test/tests/test_binops.py", line 50, in test_binops
    tx, results, total_ops, engine = TestBuild(out, ['<<', 16, -2], self.GetWallet1(), '', '07')
AssertionError: ValueError not raised
----------------------------------------------------------------------
```
@ixje has already stated his is working on a solution.

**Comment by jseagrave21** [comment]
@ixje These are the only lines of code not covered now, and I am not sure how I would mock their input: https://coveralls.io/builds/19633238/source?filename=neo/Prompt/Commands/Tokens.py#L238

Do you have any pointers or is this effort not worth the coverage?

**Comment by jseagrave21** [comment]
Never mind. I think I figured it out and I don't have to use `mock`. 👍

**Comment by jseagrave21** [comment]
Huge shoutout to @dauTT for his help moving the Notification DB setup and teardown methods into `BlockchainFixtureTestCase`. Now `Tokens.py` has (nearly) full coverage, but more importantly, tests using `WalletFixtureTestCase` have access to the Notifications DB and the Blockchain DB

**Comment by localhuman** [comment]
Looks good, but need merge conflicts resolved!

**Comment by jseagrave21** [comment]
@localhuman I resolved merge conflicts but now the build is failing because `Exception: Leveldb Unavailable`. I am trying to troubleshoot.

**Comment by jseagrave21** [comment]
@localhuman Got it! Okay, now it is ready for another review.

**Comment by ixje** [comment]
Thanks for sticking with it! 💯

**Pull request merged**
