### PR TITLE
RPC JSON Property Tweaks

### PR DESCRIPTION
**Pull request by brianlenz**
**What current issue(s) does this address, or what feature is it adding?**

As reported by @lucianoengel in Discord #neoscan-api, updated `next_consensus` JSON property to `nextconsensus`. Also completed an audit of the block and transaction JSON to make sure it complies with the C# implementation. This included adding the missing `nonce` property. The primary outstanding issue (which I've documented with todo comments) is to address incorrect size calculations.

**How did you solve this problem?**

Implemented the changes.

**How did you make sure your solution works?**

Tested it. Added tests to confirm `nonce` and `nextconsensus` are being generated properly.

**Are there any special changes in the code that we should be aware of?**

I need some direction/confirmation on how to address the block and transaction size issue to address the outstanding todo comments. Curious to get your thoughts: @localhuman @metachris 

**Please check the following, if applicable:**

- [X] Did you add any tests?
- [X] Did you run `make lint`?
- [X] Did you run `make test`?
- [X] Are you making a PR to a feature branch or development rather than master?
- [X] Did you add an entry to `CHANGELOG.rst`? (if not, please do)

### CODE REVIEW

**Comment by localhuman** [comment]
Could we remove the `Size` from the json for now, since as @ixje points out it is incorrectly/incompletely implemented at the moment?

**Comment by brianlenz** [comment]
Yeah, for sure. Sounds like that may be the best plan, and then I'll create a separate issue to redesign the `Size` calculation design per @ixje's great recommendations above.

**Comment by ixje** [comment]
perhaps for readability we might want to have some utility class along the lines of
```
uint8 = 1
uint16 = 2
uint32 = 4
uint160 = 20
uint256 = 32
```

then reading `Size()` becomes a little bit more intuitive without `magic values`. from
```
def Size(self):
    return 4 + 32
```
to 
```
def Size(self):
    return uint32 + uint256
```
Or maybe we should just have a very clear docstring for  `Size()`? Something like 
> Returns the amount of bytes the serializable data of `self` consists off 

something like that?🤔

**Comment by brianlenz** [comment]
We aren't currently including `size` in the JSON, so nothing to do there.

I created #427 to address the `size` issue, so I think this particular PR can be considered done?

**Comment by localhuman** [comment]
Looks good, and thanks for creating the issue for size calculation

**Pull request merged**
